### ISSUE TITLE
Changed db_migrator API for partitioning

### ISSUE THREAD

**Issue by laurenz** [fljdin/mysql_migrator#8]
My commit cybertec-postgresql/db_migrator@1d85415117aaab4aafa9bd8c1b36fd18dbbe6057 made some changes that affect this project:

- the column `expression` in `partitions` and `subpartitions` has been renamed to `key`
- for hash partitioning, `values` now only has to contain the remainder (I figure out the modulus from the size of the result set)

Sorry for the inconvenience.

**Comment by fljdin** [comment]
Hi Laurenz,

Latest PR commit has been sanitized to be compliant with db_migrator 1.0.0 and latest partitioning API.
It has been released as 0.2.0 :tada: 20e2bf31d72216ebe0995970c21eede1a5f626ec

As you will see, it's doing an extra UPDATE in test file which performs a expression translate for partition key. I think it could be done directly into `db_migrator`.

**Comment by laurenz** [comment]
Feel free to send a patch for db_migrator.
I'd say you can close this issue, right?
